name: "Azure Hosted Dynamic DNS"
version: "0.0.6"
slug: folder
description: >-
   "Will save the public ip address of the network you are on to azure dns,
   Must already have made a azure account and have the following information:
      AzureTenantID ClientID, ClientSecret, SubscriptionID, ResourceName, DNS Zone Name, DNS A Record to udpate, URL Of External IP Services, REGEX to get ip from response"
arch:
  - amd64
legacy: true
#image: mcr.microsoft.com/dotnet/runtime
#url: "website with more information about the add-on (e.g., a forum thread for support)"
options:
 AzureTenantID: null
 AzureClientID: null
 AzureClientSecret: null
 AzureSubID: null
 AzureResourceName: null
 DNSZoneName: null
 DNSARecordToUpdate: HA
 PollFrequency: 60000
 DNSARecordTTL: 300
 IPServiceURL: null
 URLParsingRegex: ^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\\b){4}$
schema:
 AzureTenantID: str
 AzureClientID: str
 AzureClientSecret: password
 AzureSubID: str
 AzureResourceName: str
 DNSZoneName: str
 DNSARecordToUpdate: str
 PollFrequency: int
 DNSARecordTTL: int
 IPServiceURL: str
 URLParsingRegex: str
